Surface option to not expand non-purchase ecomm events
mparticle-integrations/mparticle-android-integration-appboy pull request #80
Opened 2022-07-14 03:24 UTC by shwangMP

# Summary

For specific use cases such as abandoned cart, Braze must receive all products and associated product metadata within a single triggering event. This option can live within a config setting in the mP connection. 

Braze does not surface an native API to pass Purchase events with multiple products so Purchase events are omitted from this PR.

This PR also updates logging language from "Appboy" to "Braze" and includes custom attributes in Purchase events

2022-07-18 15:52 UTC, davidbielik commented
(Braze corresponding ticket: SDK-2816)

2022-07-21 17:47 UTC, willpassidomo requested changes
Looks great Steve! I had a couple nullability problems I caught, but other than that it's just about good to go :)

2022-07-21 17:47 UTC, willpassidomo commented on src/main/java/com/mparticle/kits/AppboyKit.java
> +                    BrazeProperties brazeProperties = new BrazeProperties(new JSONObject().put("Transaction ID", event.getTransactionAttributes().getId()).put("products", productArray));
`event.getTransactionAttributes()` is Nullable :/

```suggestion
                    JSONObject json = new JSONObject().put("products", productArray);
                    TransactionAttributes transactionAttributes = event.getTransactionAttributes();
                    if (transactionAttributes != null) {
                        json.put("Transaction ID",  transactionAttributes.getId();
                    }
                    BrazeProperties brazeProperties = new BrazeProperties(json);
```

2022-07-21 17:47 UTC, willpassidomo commented on src/main/java/com/mparticle/kits/AppboyKit.java
> +                    Map<String, Object> newAttributes = eventList.get(i).getCustomAttributes();
`MPEvent.getCustomAttributes()` is Nullable :/

```suggestion
                    Map<String, Object> newAttributes = eventList.get(i).getCustomAttributes();
                    if (newAttributes == null) {
                        newAttributes = new HashMap<>();
                    }
```

2022-07-21 18:39 UTC, davidbielik commented
Hi, wanted to let you know that the Braze SDK engineering team was asked to review this and plans to review in the next 2-3 weeks

2022-07-29 04:21 UTC, mchuangatmp commented
We migrated the kit to Kotlin so i recreated the PR and we'll track the work here: https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/82

2022-07-29 04:21 UTC, closed without merging